package sla.dao;

import java.util.List;
import sla.bean.CustomerMaster;
import sla.bean.EmployeeMaster;
import sla.bean.LocationMaster;
import sla.bean.ModelMaster;
import sla.bean.ProductMaster;
import sla.bean.SpareMaster;
import sla.bean.UnitMaster;
import sla.bean.WarrantyTracking;;
public interface AdminDao {
	public boolean CustomerSaveDao(CustomerMaster customer);
	public List<CustomerMaster> getCustomerListDao();
	public CustomerMaster getCustomerEditDao(String customerId);
	public String generateCustomerId();
	public boolean deleteCustomer(String customerId);
	public boolean EmployeeSaveDao(EmployeeMaster employee);
	public String generateEmployeeId();
	public List<EmployeeMaster> getEmployeeListDao();
	public EmployeeMaster employeeEditDao(String empId);
	public boolean deleteEmployeeDao(String empId);
	public boolean modelSaveDao(ModelMaster modelMas);
	public String generateModelId();
	public List<ModelMaster> generateModelDetailsDao();
	public List<ModelMaster> getModelListDao();
	public ModelMaster modelEditDao(String modelId);
	public boolean deleteModel(String modelId);
	public boolean productSaveDao(ProductMaster product);
	public boolean deleteProduct(String productId);
	public String generateProductId();
	public List<ProductMaster> getProductListDao();
	public ProductMaster productEditDao(String productId);
	public List<CustomerMaster> generateCustomerDetailsDao();
	public CustomerMaster getCustomerAddressDao(String customerId);
	public List<ProductMaster> generateProductDetailsDao();
	public boolean spareSaveDao(SpareMaster spare);
	public List<SpareMaster> getSpareListDao();
	public SpareMaster spareEditDao(String spareId);
	public boolean deleteSpare(String spareId);
	public String generateSpareId();
	public boolean locationSaveDao(LocationMaster locationMas);
	public String generateLocationIdDao();
	public List<LocationMaster> getLocationListDao();
	public LocationMaster locationEditDao(String locationId);
	public boolean deleteLocation(String locationId);
	public boolean unitSaveDao(UnitMaster unitMas);
	public String generateUnitId();
	public List<UnitMaster> getUnitListDao();
	public UnitMaster unitEditDao(String unitId);
	public boolean deleteUnit(String unitId);
	public boolean getCstUserName(String userName) ;
	public boolean warrantySaveDao(WarrantyTracking warranty);
	public String generateDocId();
	public List<WarrantyTracking> getWarrantyListDao();
	public WarrantyTracking warrantyEditDao(String docId);
	public boolean deleteWarranty(String docId);
}
